---
# tasks file for ansible-acmetool

- name: Add Artefactual repo key (Ubuntu)
  apt_key:
    url: "https://packages.archivematica.org/acmetool/key.asc"
    state: present
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version is version('18.04', '<=')
  tags: acmetool-install

- name: Add Ubuntu repo (version <= 16.04)
  apt_repository:
    repo: "deb [arch=amd64] http://packages.archivematica.org/acmetool/ubuntu xenial main"
    update_cache: "yes"
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version is version('16.04', '<=')
  tags: acmetool-install

# Ubuntu focal (20.04) includes acmetool in official repositories
- name: Add Ubuntu repo (version = 18.04)
  apt_repository:
    repo: "deb [arch=amd64] http://packages.archivematica.org/acmetool/ubuntu bionic main"
    update_cache: "yes"
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution_version is version('18.04', '==')
  tags: acmetool-install

- name: Install acmetool package (Ubuntu)
  apt:
    name: "acmetool"
    state: "latest"
  when: ansible_os_family == "Debian"
  tags: acmetool-install

- name: Add RedHat/CentOS/Rocky 7 repo file
  template:
    src: "acmetool_centos7.repo.j2"
    dest: "/etc/yum.repos.d/artefactual-acmetool.repo"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - ansible_os_family in ['RedHat','Rocky']
    - ansible_facts['distribution_major_version'] <= "7"
    - install_rpm_repositories|bool
  tags: acmetool-install

- name: Add RedHat/CentOS/Rocky >=8 repo file
  template:
    src: "acmetool_rocky.repo.j2"
    dest: "/etc/yum.repos.d/artefactual-acmetool.repo"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - ansible_os_family in ['RedHat','Rocky']
    - ansible_facts['distribution_major_version'] >= "7"
    - install_rpm_repositories|bool
  tags: acmetool-instal


- name: Install acmetool package (RH/CentOS/Rocky)
  yum:
    name: "acmetool"
    state: "latest"
  when: ansible_os_family in ['RedHat', 'Rocky']
  tags: acmetool-install

- name: "create dir for response file"
  file:
    name: "/var/lib/acme/conf"
    state: "directory"
  tags: acmetool-install

- set_fact:
    acmetool_responses_method: "stateless"
  when:  acmetool_websrv == "nginx"
  tags:
    - acmetool-install
    - acmetool-websrv
    - acmetool-update-response-file

- set_fact:
    acmetool_responses_method: "proxy"
  when:  acmetool_websrv == "apache"
  tags:
    - acmetool-install
    - acmetool-websrv
    - acmetool-update-response-file

- name: "copy response file"
  template:
    src: "response-file.yml.j2"
    dest: "/var/lib/acme/conf/responses"
  tags: 
    - acmetool-install
    - acmetool-update-response-file

- name: "acmetool: quickstart"
  command: "acmetool quickstart"
  tags: acmetool-install


- name: "apache specific config tasks"
  import_tasks: "apache-proxy.yml"
  when: acmetool_websrv == "apache"
  tags: acmetool-websrv

- name: "nginx specific config tasks"
  import_tasks: "nginx-stateless.yml"
  when: acmetool_websrv == "nginx"
  tags: acmetool-websrv

- name: "acmetool: want"
  command: "acmetool want {{ item }}"
  with_items: "{{ acmetool_want }}"
  tags: acmetool-websrv
  when: acmetool_want is defined

- name: "nginx specific config tasks after getting certs"
  import_tasks: "nginx-stateless-disable-temp-site.yml"
  tags: acmetool-websrv
  when:
   - acmetool_want is defined
   - acmetool_websrv == "nginx"
