---
# tasks file for ansible-acmetool

- apt_repository:
    repo: "ppa:hlandau/rhea"
    update_cache: "yes"
  when: ansible_distribution == "Ubuntu"
  tags: acmetool-install

- apt:
    name: "acmetool"
    state: "latest"
  tags: acmetool-install

- name: "create dir for response file"
  file:
    name: "/var/lib/acme/conf"
    state: "directory"
  tags: acmetool-install

- set_fact:
    acmetool_responses_method: "stateless"
  when:  acmetool_websrv == "nginx"
  tags:
    - acmetool-install
    - acmetool-websrv
    - acmetool-update-response-file

- set_fact:
    acmetool_responses_method: "proxy"
  when:  acmetool_websrv == "apache"
  tags:
    - acmetool-install
    - acmetool-websrv
    - acmetool-update-response-file

- set_fact:
    acmetool_letsencrypt_environment: "{{ 'https://acme-staging.api.letsencrypt.org/directory' if acmetool_staging else 'https://acme-v01.api.letsencrypt.org/directory' }}"

- name: "copy response file"
  template:
    src: "response-file.yml.j2"
    dest: "/var/lib/acme/conf/responses"
  tags: 
    - acmetool-install
    - acmetool-update-response-file

- name: "acmetool: quickstart"
  command: "acmetool quickstart"
  tags: acmetool-install


- name: "apache specific config tasks"
  include: "apache-proxy.yml"
  when: acmetool_websrv == "apache"
  tags: acmetool-websrv

- name: "nginx specific config tasks"
  include: "nginx-stateless.yml"
  when: acmetool_websrv == "nginx"
  tags: acmetool-websrv

- name: "acmetool: want"
  command: "acmetool want {{ item }}"
  with_items: "{{ acmetool_want }}"
  tags: acmetool-websrv

- name: "nginx specific config tasks after getting certs"
  include: "nginx-stateless-disable-temp-site.yml"
  when: acmetool_websrv == "nginx"
  tags: acmetool-websrv
