---
# tasks file for ansible-acmetool

- name: Add Ubuntu repo
  apt_repository:
    repo: "ppa:hlandau/rhea"
    update_cache: "yes"
  when: ansible_os_family == "Debian"
  tags: acmetool-install

- name: Install acmetool package (Ubuntu)
  apt:
    name: "acmetool"
    state: "latest"
  when: ansible_os_family == "Debian"
  tags: acmetool-install

- name: Add RedHat/CentOS repo file
  template:
    src: "acmetool_centos7.repo.j2"
    dest: "/etc/yum.repos.d/acmetool.repo"
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_os_family == "RedHat"
  tags: acmetool-install

- name: Install acmetool package (RH/CentOS)
  yum:
    name: "acmetool"
    state: "latest"
  when: ansible_os_family == "RedHat"
  tags: acmetool-install

- name: "create dir for response file"
  file:
    name: "/var/lib/acme/conf"
    state: "directory"
  tags: acmetool-install

- set_fact:
    acmetool_responses_method: "stateless"
  when:  acmetool_websrv == "nginx"
  tags:
    - acmetool-install
    - acmetool-websrv
    - acmetool-update-response-file

- set_fact:
    acmetool_responses_method: "proxy"
  when:  acmetool_websrv == "apache"
  tags:
    - acmetool-install
    - acmetool-websrv
    - acmetool-update-response-file

- name: "copy response file"
  template:
    src: "response-file.yml.j2"
    dest: "/var/lib/acme/conf/responses"
  tags: 
    - acmetool-install
    - acmetool-update-response-file

- name: "acmetool: quickstart"
  command: "acmetool quickstart"
  tags: acmetool-install


- name: "apache specific config tasks"
  include: "apache-proxy.yml"
  when: acmetool_websrv == "apache"
  tags: acmetool-websrv

- name: "nginx specific config tasks"
  include: "nginx-stateless.yml"
  when: acmetool_websrv == "nginx"
  tags: acmetool-websrv

- name: "acmetool: want"
  command: "acmetool want {{ item }}"
  with_items: "{{ acmetool_want }}"
  tags: acmetool-websrv

- name: "nginx specific config tasks after getting certs"
  include: "nginx-stateless-disable-temp-site.yml"
  when: acmetool_websrv == "nginx"
  tags: acmetool-websrv
